import { useState } from "react";
import { Layout } from "@/components/layout/Layout";
import { Button } from "@/components/ui/button";
import { TextAreaBox } from "@/components/ui/TextAreaBox";
import { Search, Loader2, Eye, AlertCircle } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { cn } from "@/lib/utils";
import { CircularGauge } from "@/components/ui/CircularGauge";
import { API_BASE_URL } from "@/config";

interface SentenceBreakdown {
  text: string;
  score: number;
}

interface DetectorResult {
  aiScore: number;
  humanScore: number;
  sentenceBreakdown: SentenceBreakdown[];
  analysis?: {
    patternScore: number;
    burstiScore: number;
    uniformityScore: number;
    punctuationScore: number;
    transitionScore: number;
  };
}

export default function AIDetector() {
  const [inputText, setInputText] = useState("");
  const [isProcessing, setIsProcessing] = useState(false);
  const [result, setResult] = useState<DetectorResult | null>(null);

  const charCount = inputText.length;
  const maxChars = 100000;

  const handleCheck = async () => {
    if (!inputText.trim()) {
      toast.error("Please enter some text to analyze");
      return;
    }

    if (charCount > maxChars) {
      toast.error(`Text exceeds maximum limit of ${maxChars.toLocaleString()} characters`);
      return;
    }

    setIsProcessing(true);

    try {
      const response = await fetch(`${API_BASE_URL}/api/ai-detector`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: inputText }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        const message = errorData.error || "Analysis failed";
        if (message.includes("429") || message.includes("rate limit")) {
          toast.error("Rate limit reached. Please wait a few seconds and try again.");
        } else {
          throw new Error(message);
        }
        return;
      }

      const data = await response.json();

      if (data?.error) {
        toast.error(data.error);
        return;
      }

      setResult(data as DetectorResult);
      toast.success("Analysis complete");
    } catch (error) {
      console.error("Detector error:", error);
      toast.error("Failed to analyze text. Please try again.");
    } finally {
      setIsProcessing(false);
    }
  };

  const getSummaryMessage = (score: number) => {
    if (score < 10) return "Your text is authentically human-written.";
    if (score < 30) return "Your text appears to be mostly human-written.";
    if (score < 70) return "Your text contains mixed signals, with some parts generated by AI/GPT.";
    if (score < 90) return "Your text is likely AI-generated.";
    return "Your text is almost certainly AI/GPT generated.";
  };

  const getSentenceScoreColor = (score: number) => {
    if (score <= 20) return "bg-green-500";
    if (score <= 50) return "bg-yellow-500";
    return "bg-red-500";
  };

  const getSentenceBgColor = (score: number) => {
    if (score <= 20) return "bg-green-50 border-green-200";
    if (score <= 50) return "bg-yellow-50 border-yellow-200";
    return "bg-red-50 border-red-200";
  };

  return (
    <Layout>
      <div className="container py-8 md:py-12">
        <div className="max-w-5xl mx-auto">
          {/* Header */}
          <div className="text-center mb-8">
            <h1 className="text-3xl md:text-4xl font-bold text-foreground mb-2">
              PL AI Detector
            </h1>
            <p className="text-muted-foreground">
              Analyze text to detect AI-generated content with sentence-level analysis
            </p>
          </div>

          {/* Input Section */}
          <div className="mb-8">
            <TextAreaBox
              label="Text to Analyze"
              value={inputText}
              onChange={setInputText}
              placeholder="Paste your text here to check for AI-generated content..."
              maxHeight="300px"
            />
            <div className="flex items-center justify-between mt-2">
              <span className="text-xs text-muted-foreground">
                {charCount.toLocaleString()} / {maxChars.toLocaleString()} characters
              </span>
              <Button
                variant="gradient"
                onClick={handleCheck}
                disabled={isProcessing || !inputText.trim()}
              >
                {isProcessing ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Search className="h-4 w-4" />
                )}
                Detect Text
              </Button>
            </div>
          </div>

          {/* Analysis Results */}
          {result && (
            <div className="space-y-6">
              {/* Analysis Summary - Two Column Layout */}
              <div className="grid md:grid-cols-2 gap-6">
                {/* Left: Circular Gauge */}
                <div className="bg-card rounded-2xl border border-border p-6 shadow-card flex items-center justify-center">
                  <CircularGauge score={result.aiScore} />
                </div>

                {/* Right: Analysis Summary */}
                <div className="bg-card rounded-2xl border border-border p-6 shadow-card">
                  <h3 className="text-xl font-semibold text-foreground mb-4">Analysis Summary</h3>

                  <div className="space-y-4">
                    {/* AI Generated Bar */}
                    <div>
                      <div className="flex justify-between text-sm mb-1">
                        <span className="text-foreground font-medium">AI Generated</span>
                        <span className="text-red-500 font-semibold">{result.aiScore.toFixed(1)}%</span>
                      </div>
                      <div className="h-3 bg-muted rounded-full overflow-hidden">
                        <div
                          className="h-full bg-red-500 transition-all rounded-full"
                          style={{ width: `${result.aiScore}%` }}
                        />
                      </div>
                    </div>

                    {/* Human Written Bar */}
                    <div>
                      <div className="flex justify-between text-sm mb-1">
                        <span className="text-foreground font-medium">Human Written</span>
                        <span className="text-green-500 font-semibold">{result.humanScore.toFixed(1)}%</span>
                      </div>
                      <div className="h-3 bg-muted rounded-full overflow-hidden">
                        <div
                          className="h-full bg-green-500 transition-all rounded-full"
                          style={{ width: `${result.humanScore}%` }}
                        />
                      </div>
                    </div>

                    {/* Summary Message */}
                    <div className="flex items-start gap-3 p-3 bg-muted/50 rounded-lg mt-4">
                      <AlertCircle className="h-5 w-5 text-muted-foreground flex-shrink-0 mt-0.5" />
                      <p className="text-sm text-muted-foreground">
                        {getSummaryMessage(result.aiScore)}
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Sentence-Level Analysis */}
              {result.sentenceBreakdown && result.sentenceBreakdown.length > 0 && (
                <div className="bg-card rounded-2xl border border-border p-6 shadow-card">
                  <div className="flex items-center gap-2 mb-4">
                    <Eye className="h-5 w-5 text-muted-foreground" />
                    <h3 className="text-lg font-semibold text-foreground">
                      Sentence-Level Analysis
                    </h3>
                  </div>

                  <div className="space-y-3 max-h-[400px] overflow-y-auto pr-2">
                    {result.sentenceBreakdown.map((sentence, index) => (
                      <div
                        key={index}
                        className={cn(
                          "p-4 rounded-lg border transition-all",
                          getSentenceBgColor(sentence.score)
                        )}
                      >
                        <div className="flex items-start justify-between gap-4">
                          <p className="text-foreground text-sm flex-1 leading-relaxed">
                            {sentence.text}
                          </p>
                          <span
                            className={cn(
                              "px-2.5 py-1 rounded-full text-xs font-semibold text-white flex-shrink-0",
                              getSentenceScoreColor(sentence.score)
                            )}
                          >
                            {sentence.score.toFixed(0)}% AI
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </Layout>
  );
}
